//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WUView.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WUView.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Date.
        /// </summary>
        public static string AboutBuildDate {
            get {
                return ResourceManager.GetString("AboutBuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit ID.
        /// </summary>
        public static string AboutCommitID {
            get {
                return ResourceManager.GetString("AboutCommitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Commit ID:.
        /// </summary>
        public static string AboutCommitIDToolTip {
            get {
                return ResourceManager.GetString("AboutCommitIDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string AboutCreatedBy {
            get {
                return ResourceManager.GetString("AboutCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Tim&apos;s other work at https://github.com/Timthreetwelve.
        /// </summary>
        public static string AboutCreatedByToolTip {
            get {
                return ResourceManager.GetString("AboutCreatedByToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of Windows Updates on this device.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string AboutDocumentation {
            get {
                return ResourceManager.GetString("AboutDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the ReadMe file.
        /// </summary>
        public static string AboutDocumentationToolTip {
            get {
                return ResourceManager.GetString("AboutDocumentationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the ReadMe file.
        /// </summary>
        public static string AboutDocumentionText {
            get {
                return ResourceManager.GetString("AboutDocumentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the WUView page on GitHub.
        /// </summary>
        public static string AboutGitHubToolTip {
            get {
                return ResourceManager.GetString("AboutGitHubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is licensed under the terms of the MIT license..
        /// </summary>
        public static string AboutLicenseText {
            get {
                return ResourceManager.GetString("AboutLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the license document.
        /// </summary>
        public static string AboutLicenseToolTip {
            get {
                return ResourceManager.GetString("AboutLicenseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update WUView.
        /// </summary>
        public static string AboutUpdateWU {
            get {
                return ResourceManager.GetString("AboutUpdateWU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new release of Windows Update Viewer.
        /// </summary>
        public static string AboutUpdateWUText {
            get {
                return ResourceManager.GetString("AboutUpdateWUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check GitHub for a newer release.
        /// </summary>
        public static string AboutUpdateWUToolTip {
            get {
                return ResourceManager.GetString("AboutUpdateWUToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DetailsDate {
            get {
                return ResourceManager.GetString("DetailsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DetailsDescription {
            get {
                return ResourceManager.GetString("DetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Event Log details:.
        /// </summary>
        public static string DetailsHeadingEventLog {
            get {
                return ResourceManager.GetString("DetailsHeadingEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update details:.
        /// </summary>
        public static string DetailsHeadingUpdate {
            get {
                return ResourceManager.GetString("DetailsHeadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HResult:.
        /// </summary>
        public static string DetailsHResult {
            get {
                return ResourceManager.GetString("DetailsHResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB Number:.
        /// </summary>
        public static string DetailsKBNum {
            get {
                return ResourceManager.GetString("DetailsKBNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation:.
        /// </summary>
        public static string DetailsOperation {
            get {
                return ResourceManager.GetString("DetailsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Code:.
        /// </summary>
        public static string DetailsResultCode {
            get {
                return ResourceManager.GetString("DetailsResultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support URL:.
        /// </summary>
        public static string DetailsSupportURL {
            get {
                return ResourceManager.GetString("DetailsSupportURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an update from above and the details will appear here..
        /// </summary>
        public static string DetailsTitleFallback {
            get {
                return ResourceManager.GetString("DetailsTitleFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ID:.
        /// </summary>
        public static string DetailsUpdateID {
            get {
                return ResourceManager.GetString("DetailsUpdateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DGColDate {
            get {
                return ResourceManager.GetString("DGColDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB Number.
        /// </summary>
        public static string DGColKBNum {
            get {
                return ResourceManager.GetString("DGColKBNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string DGColResult {
            get {
                return ResourceManager.GetString("DGColResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string DGColTitle {
            get {
                return ResourceManager.GetString("DGColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter strings to exclude (one per line).
        /// </summary>
        public static string ExcludesEditorTextLine1 {
            get {
                return ResourceManager.GetString("ExcludesEditorTextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparisons are not case sensitive.
        /// </summary>
        public static string ExcludesEditorTextLine2 {
            get {
                return ResourceManager.GetString("ExcludesEditorTextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Grid to Clipboard.
        /// </summary>
        public static string MenuItemCopyToClipboard {
            get {
                return ResourceManager.GetString("MenuItemCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exclude List.
        /// </summary>
        public static string MenuItemEditExclude {
            get {
                return ResourceManager.GetString("MenuItemEditExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larger View.
        /// </summary>
        public static string MenuItemLarger {
            get {
                return ResourceManager.GetString("MenuItemLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Update.
        /// </summary>
        public static string MenuItemOpenWindowsUpdate {
            get {
                return ResourceManager.GetString("MenuItemOpenWindowsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Updates.
        /// </summary>
        public static string MenuItemRefresh {
            get {
                return ResourceManager.GetString("MenuItemRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Column Sort.
        /// </summary>
        public static string MenuItemRemoveSort {
            get {
                return ResourceManager.GetString("MenuItemRemoveSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Grid to CSV File.
        /// </summary>
        public static string MenuItemSaveCSV {
            get {
                return ResourceManager.GetString("MenuItemSaveCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Details to Text File.
        /// </summary>
        public static string MenuItemSaveTXT {
            get {
                return ResourceManager.GetString("MenuItemSaveTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller View.
        /// </summary>
        public static string MenuItemSmaller {
            get {
                return ResourceManager.GetString("MenuItemSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Details Pane.
        /// </summary>
        public static string MenuItemToggleDetails {
            get {
                return ResourceManager.GetString("MenuItemToggleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Excluded Items.
        /// </summary>
        public static string MenuItemToggleExcluded {
            get {
                return ResourceManager.GetString("MenuItemToggleExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavItemAbout {
            get {
                return ResourceManager.GetString("NavItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string NavItemExit {
            get {
                return ResourceManager.GetString("NavItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavItemSettings {
            get {
                return ResourceManager.GetString("NavItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string NavItemUpdates {
            get {
                return ResourceManager.GetString("NavItemUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Windows Update Viewer.
        /// </summary>
        public static string NavTitleAbout {
            get {
                return ResourceManager.GetString("NavTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavTitleSettings {
            get {
                return ResourceManager.GetString("NavTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update Viewer.
        /// </summary>
        public static string NavTitleUpdates {
            get {
                return ResourceManager.GetString("NavTitleUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Language will cause application to restart!.
        /// </summary>
        public static string SettingsPageChangingLanguageWarning {
            get {
                return ResourceManager.GetString("SettingsPageChangingLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift-Click to open file with default application.
        /// </summary>
        public static string SettingsPageEditExcludeToolTip {
            get {
                return ResourceManager.GetString("SettingsPageEditExcludeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsPageLanguage {
            get {
                return ResourceManager.GetString("SettingsPageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Updates.
        /// </summary>
        public static string SettingsPageNumberOfUpdates {
            get {
                return ResourceManager.GetString("SettingsPageNumberOfUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Display Language.
        /// </summary>
        public static string SettingsPageUseOSLanguageCheckBox {
            get {
                return ResourceManager.GetString("SettingsPageUseOSLanguageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string SettingsSectionAppSettings {
            get {
                return ResourceManager.GetString("SettingsSectionAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsSectionLanguage {
            get {
                return ResourceManager.GetString("SettingsSectionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Settings.
        /// </summary>
        public static string SettingsSectionUISettings {
            get {
                return ResourceManager.GetString("SettingsSectionUISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Updates, Date Format, Excluded Items, Details, &amp; more.
        /// </summary>
        public static string SettingsSubHeadAppSettings {
            get {
                return ResourceManager.GetString("SettingsSubHeadAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings (Work in Progress).
        /// </summary>
        public static string SettingsSubHeadLanguage {
            get {
                return ResourceManager.GetString("SettingsSubHeadLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme, Accent Color, UI Size, Row Height, Start Position &amp; more.
        /// </summary>
        public static string SettingsSubHeadUISettings {
            get {
                return ResourceManager.GetString("SettingsSubHeadUISettings", resourceCulture);
            }
        }
    }
}
