name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get version
        id: get-version
        run: |
          # Finding the version from release tag name
          $VERSION="${{ github.event.release.tag_name }}" -replace '^v?((?:\d+\.)+\d+)$','$1' -replace '^((?:\d+\.){2}\d+)$', '$1.0'
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Timthreetwelve.WUView
          version: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
